In [151]:
#imorting standard libraries

In [152]:
import numpy as np
import pandas as pd
import nltk
import re



In [153]:
# importing dataset and labeling the dataset
#the dataset contain two part ,firstcolumn contain the message is spam or ham . second column contain message'''

df =pd.read_csv("smsspamcollection/SMSSpamCollection", sep='\t',names=["label","message"])
df


label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [154]:
messages =df
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [155]:
#Data cleaning and Preprocessing
# above the data contain the comma,fullstops,numbers,question marks and stopwords we need remove this

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


corpus =[]

for i in range(0,len(messages)):
    new_data = re.sub('[^a-zA-Z]',' ',messages['message'][i])  # remove all except a-z and A-Z and replace " "
    new_data = new_data.lower()
    new_data = new_data.split()
    
    new_data = [ps.stem(word) for word in new_data if not word in stopwords.words('english')]
    new_data = ' '.join(new_data)
    corpus.append(new_data)
    


In [171]:
#Create the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000)
x = cv.fit_transform(corpus).toarray()



In [172]:
# our dependent variable is label it's contain text hence our model not undestand that hence we create dummy values

df1 = pd.get_dummies(messages['label'])
df1

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [173]:
# if ham=1  it's ham and ham =0 it's spam  . 
# if spam =1  it's spam  and spam=0 it's ham
# both are hence we delete anyone column bcz both are telling same story

df2= df1.iloc[:,1].values
y=df2
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [174]:
# split the data into train and test part

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size =0.2, random_state=0)



In [175]:
### Train a model using Logestic Regression

from sklearn.linear_model import LogisticRegression
spam_detect_model1 = LogisticRegression()
spam_detect_model1.fit(x_train,y_train)

LogisticRegression()

In [176]:
confusion_matrix(y_test,spam_detect_model1.predict(x_test))

array([[954,   1],
       [ 16, 144]], dtype=int64)

#####  Actuallt this model give  16 type-2 error   and  1 type-1 error = totally 17 errors

In [177]:
# model accuracy checking

y_predict= spam_detect_model1.score(x_test,y_test)
y_predict

0.9847533632286996

In [178]:
accuracy_score(y_test,spam_detect_model1.predict(x_test))

0.9847533632286996

####  LogisticRegression gives the 98.47% Accuracy

# ---Lets try with another Algorithm's

In [179]:
### 2.Train a model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB()
spam_detect_model.fit(x_train,y_train)

MultinomialNB()

In [180]:
y_pred = spam_detect_model.predict(x_test)

In [181]:
# Model Efficiency checking

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[946,   9],
       [  8, 152]], dtype=int64)

In [182]:
## woh!!! this model also give totally 17 errors  but  9 type-1  and 8 type-2 error

In [183]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9847533632286996

### This module also give same Acuuracy of 98.47%